# Generated by Django 5.2.5 on 2025-08-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_excelupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberentry',
            name='middle_num',
            field=models.IntegerField(blank=True, help_text='Optional middle number if available', null=True),
        ),
    ]
